name: Talk to Azure

on:
  workflow_dispatch



permissions:
    id-token: write
    contents: read

  
jobs:
  connectazure:
    runs-on: ubuntu-latest
    environment: AzureSub

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az group create -n ${{ vars.RGNAME}}  -l   ${{ vars.RGLOCATION }}
          
