name: Talk to Azure

on:
  workflow_dispatch



permissions:
    id-token: write
    contents: read

  
jobs:
  connectazure:
    runs-on: ubuntu-latest
    environment: AzureSub

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az group create -n ${{ vars.RGNAME }} -l ${{ vars.RGLOCATION }}


      # Deploy Bicep file
      - name: deploy
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.RGNAME }}
          template: ./main.bicep
          parameters: 'storagePrefix=mystore${{github.run_id}} storageSKU=Standard_LRS'
          failOnStdErr: false


      - name: 'Display result'
        run: echo ${{ steps.deploy.outputs.resourceName }}

      - name: 'Delete resource'
        run: |
          echo ${{ steps.deploy.outputs.id }}
          az resource delete --ids ${{ steps.deploy.outputs.id }}
      